version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - master
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Send Via SFTP
          command: lftp -p 5022 sftp://didiuxwq:HQGhbv3BEVmzk4@world-331.fr.planethoster.net -e "mirror -R ./ /home/didiuxwq/tmp; quit";
            
