version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: sudo apt update

  lint:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: sudo apt update

  test:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run: sudo apt update

workflows:
  version: 2
  integration:
    jobs:
      - build
      - lint
      - test
