jobs:
  build:
  deploy:
    docker:
      - image: circleci/php:7.2-browsers
    working_directory: /var/www/html
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "AAAAB3NzaC1yc2EAAAADAQABAAABAQDL+QgFKHq24zypfhOhvGP8ZbhJ9utRRm62O3DMB8cBvWbQoXf1anc5z7k2XzQyGlUij4XQnJj0z16dBJLGGadmd0sHf/HFMVr44oT/oZ8gQnieIJrAiNP7P7CbTN4IOBffYFKwS+jeH9y5n4ppb55JsTGWEKg6+0dqVZz28Li3qw5HhNdJd51FGFMvE7hy15V0p8c9Xg1vGAjz3I7DeY/LKvEFtU0kW4u0Cl/V9HJcj06uineR2x8MURfF5LIQJuNZSTmq41VGjVhHg1EUnnjtx/MYDI5XOOcXkwod4PLLILMW/EeBVid5AyMQgql8BSmALpkbRGOytECmKpecO5AJ"
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            sudo mv deployer.phar /usr/local/bin/dep
            sudo chmod +x /usr/local/bin/dep
      - run:
          name: Deploy
          command: |
            dep deploy world-331.fr.planethoster.net
